'use strict';
const $ = id => document.getElementById(id);
const storageKey = 'panki-apartments-2026-10-09:viewed:v1';
const reducedMotion = window.matchMedia('(prefers-reduced-motion: reduce)');
const mobile = window.matchMedia('(max-width: 760px)');
const icons = {
 check:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="m5 12 4 4L19 6"/></svg>',
 close:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="m6 6 12 12M18 6 6 18"/></svg>',
 left:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="m14 6-6 6 6 6"/></svg>',
 right:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="m10 6 6 6-6 6"/></svg>',
 house:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="m3 10 9-7 9 7M5 9v12h14V9M9 21v-7h6v7"/></svg>',
 eye:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M2 12s4-7 10-7 10 7 10 7-4 7-10 7S2 12 2 12Z"/><circle cx="12" cy="12" r="3"/></svg>'
};
const esc = value => String(value ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const number = value => new Intl.NumberFormat('ru-RU',{maximumFractionDigits:1}).format(value);
const price = r => r.price === null ? 'Цена не подтверждена' : number(r.price)+' ₽';
const addressShort = r => r.verified ? r.address.replace(/^(Люберцы|Томилино),\s*/,'') : 'Томилино · адрес уточняется';
const yandex = r => 'https://yandex.ru/maps/?text='+encodeURIComponent('Московская область, '+(r.verified?r.address:'Томилино'));
let apartments=[], seen=new Set(), filter='all', query='', selected=null, map=null, markers=[], photoIndex=0, toastTimer, dialogMode=null, closeTimer, storageAvailable=true;
try { const saved=JSON.parse(localStorage.getItem(storageKey)||'[]'); if(Array.isArray(saved)) seen=new Set(saved.filter(n=>Number.isInteger(n)&&n>=1&&n<=12)); } catch { storageAvailable=false; }
function toast(message){clearTimeout(toastTimer);$('toast').textContent=message;$('toast').classList.add('show');toastTimer=setTimeout(()=>$('toast').classList.remove('show'),3200);}
function persist(){try{localStorage.setItem(storageKey,JSON.stringify([...seen]));}catch{if(storageAvailable)toast('Браузер не сохраняет отметки. Они доступны до закрытия страницы.');storageAvailable=false;}}
function visibleApartments(){return apartments.filter(r=>(filter==='all'||(filter==='seen'?seen.has(r.n):!seen.has(r.n)))&&(!query||(r.address+' '+r.n+' '+r.area).toLocaleLowerCase('ru').includes(query)));}
function updateCounts(){const count=seen.size;$('viewedCount').textContent=count;$('progressText').textContent=count+' из 12';$('progressRing').style.setProperty('--progress',(count/12*360)+'deg');$('seenCount').textContent=count;$('unseenCount').textContent=12-count;$('resetButton').disabled=!count;}
function renderList(){const rows=visibleApartments();$('listingList').innerHTML=rows.length?rows.map(r=>`<button class="listing" type="button" data-id="${r.n}" id="listing-${r.n}" aria-current="${r.n===selected}" aria-label="Вариант ${r.n}, ${esc(r.address)}, ${esc(price(r))}${seen.has(r.n)?', карточку открывали':''}"><span>${r.photos.length?`<img class="listing-photo" src="${esc(r.photos[Math.min(1,r.photos.length-1)])}" alt="Квартира ${r.n}" loading="lazy">`:`<span class="listing-photo-placeholder">${icons.house}</span>`}</span><span class="listing-body"><span class="listing-line"><span class="listing-num">№ ${r.n}${r.rooms===4?' · 4 комн.':''}</span>${seen.has(r.n)?`<span class="listing-seen">${icons.check}Открывали</span>`:''}</span><span class="listing-price">${esc(price(r))}</span><span class="listing-address">${esc(addressShort(r))}</span><span class="listing-metrics">${number(r.area)} м² · ${esc(r.floorLabel||r.floor+'/'+r.floors)}${!r.verified?' · по ссылке':''}</span>${r.geoAccuracy==='approximate'?'<span class="location-warning">≈ Положение корпуса уточняется</span>':''}${!r.verified?'<span class="location-warning">Данные не подтверждены</span>':''}</span></button>`).join(''):`<div class="empty"><strong>${query?'Ничего не найдено':filter==='unseen'?'Все карточки уже открыты':'Пока нет просмотренных'}</strong>${query?'Попробуй другую улицу или номер.':filter==='unseen'?'Можно вернуться к общему списку.':'Открой номер на карте или вариант в списке.'}<button type="button" id="showAllButton">Показать все варианты</button></div>`;
 $('listingList').querySelectorAll('[data-id]').forEach(b=>b.addEventListener('click',()=>openApartment(Number(b.dataset.id))));$('showAllButton')?.addEventListener('click',()=>{query='';$('searchInput').value='';setFilter('all');});
}
function renderMarkers(){if(!map)return;markers.forEach(m=>m.remove());markers=[];const rows=visibleApartments().filter(r=>r.coordinates);const groups=new Map();for(const r of rows){const key=r.coordinates.join(',');if(!groups.has(key))groups.set(key,[]);groups.get(key).push(r);}const coordinateGroups=[...groups.values()];const joined=[];for(const group of coordinateGroups){let target=joined.find(g=>g.some(a=>group.some(b=>map.latLngToLayerPoint(a.coordinates).distanceTo(map.latLngToLayerPoint(b.coordinates))<56)));if(map.getZoom()>=15)target=null;if(target)target.push(...group);else joined.push([...group]);}for(const group of joined){
 if(new Set(group.map(r=>r.coordinates.join(','))).size>1){const bounds=L.latLngBounds(group.map(r=>r.coordinates));const countViewed=group.filter(r=>seen.has(r.n)).length;const html=`<div class="pin-group"><button class="cluster-pin ${countViewed===group.length?'seen':''}" type="button" aria-label="Группа вариантов ${group.map(r=>r.n).join(', ')}; открывали ${countViewed} из ${group.length}. Приблизить"><b>${group.length}</b><span>вариантов</span></button></div>`;const marker=L.marker(bounds.getCenter(),{icon:L.divIcon({html,className:'apartment-marker',iconSize:[0,0],iconAnchor:[0,0]}),keyboard:false}).addTo(map);markers.push(marker);const el=marker.getElement();L.DomEvent.disableClickPropagation(el);el.querySelector('button').addEventListener('click',()=>map.fitBounds(bounds,{padding:[65,95],maxZoom:16,animate:!reducedMotion.matches,duration:.65}));continue;}

 const markup=`<div class="pin-group ${group.length>1?'multi':''}">${group.map(r=>`<button class="pin ${seen.has(r.n)?'seen':''} ${selected===r.n?'selected':''} ${r.geoAccuracy==='approximate'?'approx':''}" type="button" data-pin="${r.n}" aria-label="Вариант ${r.n}: ${esc(r.address)}${seen.has(r.n)?', карточку открывали':''}${r.geoAccuracy==='approximate'?', приблизительное положение':''}" title="№${r.n} · ${esc(price(r))}">${r.geoAccuracy==='approximate'?'<span>≈</span>':''}${r.n}${seen.has(r.n)?icons.check:''}</button>`).join('')}</div>`;
 const marker=L.marker(group[0].coordinates,{icon:L.divIcon({html:markup,className:'apartment-marker',iconSize:[0,0],iconAnchor:[0,0]}),keyboard:false,zIndexOffset:group.some(r=>r.n===selected)?900:100}).addTo(map);markers.push(marker);const el=marker.getElement();L.DomEvent.disableClickPropagation(el);el.querySelectorAll('[data-pin]').forEach(b=>b.addEventListener('click',e=>{e.stopPropagation();openApartment(Number(b.dataset.pin));}));
 }$('mapCount').textContent=rows.length?rows.length+' '+(rows.length===1?'вариант':rows.length<5?'варианта':'вариантов')+' на карте':'Нет вариантов на карте';}
function render(){updateCounts();renderList();renderMarkers();}
function setFilter(value){filter=value;document.querySelectorAll('[data-filter]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.filter===filter)));render();}
function fitMap(){if(!map)return;const rows=visibleApartments().filter(r=>r.coordinates);if(rows.length)map.fitBounds(L.latLngBounds(rows.map(r=>r.coordinates)),{paddingTopLeft:[45,80],paddingBottomRight:[45,mobile.matches?160:110],maxZoom:16,animate:!reducedMotion.matches,duration:.65});else toast('В выбранном списке нет вариантов с известным адресом.');}
function initMap(){if(typeof L==='undefined'){ $('mapError').hidden=false;setMode('list');return; }map=L.map('map',{zoomControl:false,scrollWheelZoom:true,attributionControl:true,zoomAnimation:!reducedMotion.matches,fadeAnimation:!reducedMotion.matches}).setView([55.666,37.920],14);L.control.zoom({position:'bottomright'}).addTo(map);let failures=0;const tiles=L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener noreferrer">OpenStreetMap</a>',detectRetina:false}).addTo(map);tiles.on('tileerror',()=>{if(++failures>=3)$('mapError').hidden=false;});tiles.on('tileload',()=>{$('mapError').hidden=true;failures=0;});map.on('zoomend',renderMarkers);renderMarkers();fitMap();}
function detailMarkup(r){const index=apartments.findIndex(a=>a.n===r.n),isSeen=seen.has(r.n);return `<div class="detail-toolbar"><span class="detail-tag">Вариант ${r.n} из 12 · ${r.rooms} комнаты</span><div class="detail-tools"><button class="small-button" id="prevApartment" type="button" aria-label="Предыдущая квартира" ${index===0?'disabled':''}>${icons.left}</button><button class="small-button" id="nextApartment" type="button" aria-label="Следующая квартира" ${index===apartments.length-1?'disabled':''}>${icons.right}</button><button class="small-button" id="closeDetail" type="button" aria-label="Закрыть карточку">${icons.close}</button></div></div>${r.photos.length?`<div class="detail-gallery"><img id="galleryPhoto" src="${esc(r.photos[photoIndex])}" alt="Фото ${photoIndex+1} квартиры ${r.n}">${r.photos.length>1?`<button class="gallery-nav prev" id="prevPhoto" type="button" aria-label="Предыдущее фото">${icons.left}</button><button class="gallery-nav next" id="nextPhoto" type="button" aria-label="Следующее фото">${icons.right}</button>`:''}<span class="gallery-count" id="photoCount">${photoIndex+1} / ${r.photos.length}</span></div>`:`<div class="detail-placeholder">${icons.house}<span>Фотографии пока не подтверждены</span></div>`}<div class="detail-body"><div class="detail-city">${esc(r.address.split(',')[0].split(' - ')[0])}</div><h2 id="detailTitle">${esc(r.verified?addressShort(r):'Точный адрес не подтверждён')}</h2><div class="detail-price">${esc(price(r))}</div><div class="detail-metrics"><div><b>${number(r.area)} м²${r.verified?'':'*'}</b><small>общая площадь</small></div><div><b>${esc(r.floorLabel||r.floor+'/'+r.floors)}${r.verified?'':'*'}</b><small>этаж / этажность</small></div><div><b>${r.kitchen?number(r.kitchen)+' м²':'уточняется'}</b><small>кухня</small></div></div>${r.verified?`<p class="detail-copy"><b>Почему посмотреть</b>${esc(r.why)}</p><div class="check-note"><b>Что уточнить</b>${esc(r.check)}</div>`:`<div class="check-note"><b>Карточку проверить не удалось</b>Авито ограничил доступ. *Площадь, число комнат и этаж взяты только из названия ссылки. Цена, адрес, планировка и состояние требуют проверки; соответствие критериям пока не оценено.</div>`}${r.locationNote?`<div class="approx-note">${esc(r.locationNote)}</div>`:''}<div class="detail-links"><a href="${esc(r.url)}" target="_blank" rel="noopener noreferrer">Объявление · ${esc(r.source)}</a><a href="${esc(yandex(r))}" target="_blank" rel="noopener noreferrer">Яндекс Карты${r.verified?'':' · посёлок'}</a></div><button class="seen-toggle ${isSeen?'':'unseen'}" id="seenToggle" type="button" aria-pressed="${isSeen}">${isSeen?icons.check:icons.eye}<span>${isSeen?'Открывали · снять отметку':'Отметить как просмотренную'}</span></button><p class="detail-date">${r.verified?'Проверка объявления: 09.10.2026. Цену и наличие уточнить перед просмотром.':'Добавлено по ссылке. Данные не подтверждены.'}<br>«Открывали» означает просмотр этой карточки, а не посещение квартиры.</p></div>`;}
function bindDetail(r){$('closeDetail').addEventListener('click',()=>closeDetail());$('prevApartment').addEventListener('click',()=>openApartment(r.n-1));$('nextApartment').addEventListener('click',()=>openApartment(r.n+1));$('seenToggle').addEventListener('click',()=>{if(seen.has(r.n))seen.delete(r.n);else seen.add(r.n);persist();render();updateSeenButton(r);});$('prevPhoto')?.addEventListener('click',()=>changePhoto(-1,r));$('nextPhoto')?.addEventListener('click',()=>changePhoto(1,r));}
function updateSeenButton(r){const isSeen=seen.has(r.n);$('seenToggle').classList.toggle('unseen',!isSeen);$('seenToggle').setAttribute('aria-pressed',String(isSeen));$('seenToggle').innerHTML=(isSeen?icons.check:icons.eye)+`<span>${isSeen?'Открывали · снять отметку':'Отметить как просмотренную'}</span>`;}
function changePhoto(delta,r){photoIndex=(photoIndex+delta+r.photos.length)%r.photos.length;const img=$('galleryPhoto');img.style.opacity='.35';img.onload=()=>{img.style.opacity='1';};img.onerror=()=>{img.style.opacity='1';toast('Фото не загрузилось. Открой объявление.');};img.src=r.photos[photoIndex];img.alt=`Фото ${photoIndex+1} квартиры ${r.n}`;$('photoCount').textContent=`${photoIndex+1} / ${r.photos.length}`;}
function openApartment(n,{pan=true}={}){const r=apartments.find(a=>a.n===n);if(!r)return;clearTimeout(closeTimer);selected=n;photoIndex=0;seen.add(n);persist();render();$('detailContent').innerHTML=detailMarkup(r);bindDetail(r);const dlg=$('detailDialog');const nextMode=mobile.matches?'modal':'normal';if(dlg.open&&dialogMode!==nextMode)dlg.close();if(!dlg.open){nextMode==='modal'?dlg.showModal():dlg.show();dialogMode=nextMode;}requestAnimationFrame(()=>dlg.classList.add('visible'));dlg.scrollTop=0;$('closeDetail').focus({preventScroll:true});history.replaceState(null,'','#apartment='+n);if(pan&&map&&r.coordinates){const targetZoom=Math.max(map.getZoom(),15);const point=map.project(r.coordinates,targetZoom);if(!mobile.matches)point.x+=Math.min(190,map.getSize().x*.23);map.flyTo(map.unproject(point,targetZoom),targetZoom,{animate:!reducedMotion.matches,duration:.7});}}
function closeDetail(){const n=selected;const dlg=$('detailDialog');dlg.classList.remove('visible');closeTimer=setTimeout(()=>{dlg.close();selected=null;render();history.replaceState(null,'',location.pathname+location.search);$('listing-'+n)?.focus({preventScroll:true});},reducedMotion.matches?0:180);}
$('detailDialog').addEventListener('cancel',e=>{e.preventDefault();closeDetail();});$('detailDialog').addEventListener('click',e=>{if(e.target===$('detailDialog')){const box=e.target.getBoundingClientRect();if(e.clientX<box.left||e.clientX>box.right||e.clientY<box.top||e.clientY>box.bottom)closeDetail();}});
function setMode(mode){document.body.classList.toggle('list-mode',mode==='list');$('listTab').setAttribute('aria-pressed',String(mode==='list'));$('mapTab').setAttribute('aria-pressed',String(mode==='map'));if(mode==='map'&&map)requestAnimationFrame(()=>map.invalidateSize({animate:false}));}
$('listTab').addEventListener('click',()=>setMode('list'));$('mapTab').addEventListener('click',()=>setMode('map'));$('fitButton').addEventListener('click',()=>{if($('detailDialog').open)closeDetail();fitMap();});$('searchInput').addEventListener('input',e=>{query=e.target.value.trim().toLocaleLowerCase('ru');render();});document.querySelectorAll('[data-filter]').forEach(b=>b.addEventListener('click',()=>setFilter(b.dataset.filter)));
$('shareButton').addEventListener('click',async()=>{try{await navigator.clipboard.writeText(location.origin+location.pathname);toast('Ссылка скопирована');}catch{toast('Скопируй ссылку из адресной строки браузера.');}});
$('resetButton').addEventListener('click',()=>$('resetDialog').showModal());$('cancelReset').addEventListener('click',()=>$('resetDialog').close());$('confirmReset').addEventListener('click',()=>{seen.clear();persist();render();if(selected){const r=apartments.find(a=>a.n===selected);updateSeenButton(r);}$('resetDialog').close();toast('Отметки сброшены');});
mobile.addEventListener('change',()=>{if(map)requestAnimationFrame(()=>{map.invalidateSize({animate:false});if(!selected)fitMap();});if(selected&&$('detailDialog').open)openApartment(selected,{pan:false});});
async function boot(){try{const response=await fetch('data.json');if(!response.ok)throw new Error('data');const data=await response.json();if(!Array.isArray(data.apartments)||data.apartments.length!==12)throw new Error('data');apartments=data.apartments;render();initMap();const match=location.hash.match(/^#apartment=(\d+)$/);if(match)openApartment(Number(match[1]));if(!storageAvailable)toast('Отметки не сохраняются в этом браузере.');}catch(error){$('listingList').innerHTML='<div class="empty"><strong>Не удалось загрузить подборку</strong>Проверь интернет и обнови страницу.<br><a href="selection.pdf">Открыть PDF</a><br><button type="button" onclick="location.reload()">Попробовать снова</button></div>';$('mapError').hidden=false;$('mapError').textContent='Подборка не загрузилась. Обнови страницу или открой PDF.';setMode('list');}}
boot();
